#!/bin/bash

mkdir /lib/Auth
mkdir /lib/Auth/Facerec
mkdir /lib/Auth/Facerec/roots

sudo apt-get install python-pip python3-pip cmake libatlas-base-dev build-essential

sudo -H pip install execnet

sudo -H pip3 --no-cache-dir install cmake wheel setuptools terminaltables opencv-python face_recognition

